name: 🦖 Deploy tesseract.no
on:
  push:
    branches:
      - deploy_frontend
  workflow_dispatch:
jobs:
  play-deploy:
    name: 🍜 Deploy tesseract.no to do_server VPS
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest container, and restart it
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DO_VPS_IP }} # VPS IP address from GitHub Secrets
          username: "root" # VPS username from GitHub Secrets
          password: ${{ secrets.DO_VPS_PASSWORD }}
          port: 22 # SSH port (default is 22)
          script: |
            docker pull ivanmachine/tesseract.no:latest
            docker stop tesseract.no || true  # stop existing container if running
            docker rm tesseract.no || true    # remove existing container if exists
            docker run -d --name tesseract.no -p 4110:3000 ivanmachine/tesseract.no:latest
